name: aws-ses-sns-route53-backup

on:
  workflow_dispatch:
    inputs:
      chosen_env:
        required: true
        type: choice
        options:
          - stage
          - prod
          - dev

jobs:
  aws-ses-sns-route53-backup:
    name: Backup Workflow for ${{ github.event.inputs.chosen_env }}  # Dynamic job name based on the chosen environment
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write

    env:
      REGION: ${{ secrets.aws_region }}
      IAM_ROLE: ${{ secrets.iam_role }}
      SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: github-actions-federation
          aws-region: ${{ env.REGION }}

      - name: Get AWS Account Name
        id: account-info
        run: |
          aws_account_name=$(aws sts get-caller-identity --query "Arn" --output text | awk -F '/' '{print $2}')
          echo "aws_account_name=$aws_account_name" >> $GITHUB_ENV

      - name: Take Route 53 Backup
        id: backup
        run: |
          timestamp=$(date +"%Y%m%d-%H%M%S")
          account_folder="${{ env.aws_account_name }}"
          route53_folder="${account_folder}/route53-records"
          mkdir -p "$route53_folder"

          hosted_zones=$(aws route53 list-hosted-zones --query 'HostedZones[*].[Name]' --output text)

          echo "$hosted_zones" | while read -r hosted_zone_name; do
            hosted_zone_name=$(echo $hosted_zone_name | sed 's/\.$//')
            hosted_zone_id=$(aws route53 list-hosted-zones --query "HostedZones[?Name=='${hosted_zone_name}.'].Id" --output text | awk -F'/' '{print $3}')
            backup_file="${route53_folder}/${hosted_zone_name}.json"
            aws route53 list-resource-record-sets --hosted-zone-id $hosted_zone_id --output json > "$backup_file"
          done

          ls "$route53_folder"
          echo "timestamp=${timestamp}" >> $GITHUB_ENV

      - name: Take SES Backup
        id: ses-backup
        run: |
          ses_folder="${{ env.aws_account_name }}/ses-backup"
          mkdir -p "$ses_folder"

          aws ses list-identities --output json > "${ses_folder}/identities.json"

          ls "$ses_folder"

      - name: Take SNS Backup
        id: sns-backup
        run: |
          sns_folder="${{ env.aws_account_name }}/sns-backup"
          mkdir -p "$sns_folder"

          aws sns list-topics --output json > "${sns_folder}/topics.json"
          topics=$(aws sns list-topics --query 'Topics[*].TopicArn' --output text)
          for topic in $topics; do
            aws sns list-subscriptions-by-topic --topic-arn "$topic" --output json > "${sns_folder}/subscriptions_$(basename $topic).json"
            aws sns get-topic-attributes --topic-arn "$topic" --output json > "${sns_folder}/attributes_$(basename $topic).json"
          done

          ls "$sns_folder"

      - name: Check for Changes
        id: check-changes
        run: |
          changes_detected=false
          git diff --exit-code -- "${{ env.aws_account_name }}/route53-records/*" || echo "changes_detected=true" >> $GITHUB_ENV
          git diff --exit-code -- "${{ env.aws_account_name }}/ses-backup/*" || echo "changes_detected=true" >> $GITHUB_ENV
          git diff --exit-code -- "${{ env.aws_account_name }}/sns-backup/*" || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Commit and Push Backup json-files to repo
        if: env.changes_detected == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "route53backup_${{ env.timestamp }}"
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Backup Status
        run: |
          if [ "${{ env.changes_detected }}" == "true" ]; then
            message="The Route 53 and SES backups were successfully completed and committed to the repository."
          else
            message="The Route 53 and SES backups were completed, but there were no changes to commit."
          fi
          aws sns publish --topic-arn ${{ env.SNS_TOPIC_ARN }} \
            --subject "Backup Status" \
            --message "$message"
        env:
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}

      - name: Send Failure Notification
        if: failure()
        run: |
          aws sns publish --topic-arn ${{ env.SNS_TOPIC_ARN }} \
          --subject "Route 53 Backup Failed!!!" \
          --message "The Route 53 backup failed on ${timestamp}. Please check the GitHub Actions logs for more details."
        env:
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
